### ISSUE TITLE
Update URL for Last.fm

### ISSUE THREAD

**Issue by codysherman** [tgwizard/sls#8]
On Last.fm, clicking the "Simple Last.fm Scrobbler" link seen when someone is using it to scrobble goes to the Google page, not this github one.

**Comment by HumbleBeeBumbleBee** [comment]
I queried the Last.fm staff about this. I'll report back ASAP.

**Comment by tgwizard** [comment]
I've updated the URL in the Last.fm API Developer portal, and this should now be fixed. Could anyone please verify?

**Comment by tgwizard** [comment]
Apparently the link hasn't changed (thanks @HumbleBeeBumbleBee). We'll wait a while and see if it does, otherwise we'll contact Last.fm support.

**Comment by HumbleBeeBumbleBee** [comment]
I am going to close this because it seems the device which is scrobbling the music is no longer shown on the new website. I will reopen this discussion if that last.fm app scrobble link returns and is still wrong.
